export const Abbreviations = {
    serviceAce: {
        key: 'serviceAce',
        name: 'Service Ace',
        label: 'SA',
        type: 'serve',
    },
    serviceZero: {
        key: 'serviceZero',
        name: 'Service Zero',
        label: 'SZ',
        type: 'serve',
    },
    serviceError: {
        key: 'serviceError',
        name: 'Service Error',
        label: 'SE',
        type: 'serve',
    },
    serviceAttempts: {
        key: 'serviceAttempts',
        name: 'Service Attempts',
        label: 'SATT',
        type: 'serve',
    },
    serviceAcePercentage: {
        key: 'serviceAcePercentage',
        name: 'Service Ace %',
        label: 'SA%',
        type: 'serve',
    },
    servicePercentage: {
        key: 'servicePercentage',
        name: 'Service %',
        label: 'S%',
        type: 'serve',
    },
    attackKill: {
        key: 'attackKill',
        name: 'Attack Kill',
        label: 'K',
        type: 'attack',
    },
    attackZero: {
        key: 'attackZero',
        name: 'Attack Zero',
        label: 'AZ',
        type: 'attack',
    },
    attackError: {
        key: 'attackError',
        name: 'Attack Error',
        label: 'E',
        type: 'attack',
    },
    attackTotal: {
        key: 'attackTotal',
        name: 'Total Attack Attempts',
        label: 'TA',
        type: 'attack',
    },
    attackKillPercentage: {
        key: 'attackKillPercentage',
        name: 'Attack Kill %',
        label: 'K%',
        type: 'attack',
    },
    attackPercentage: {
        key: 'attackPercentage',
        name: 'Hitting %',
        label: 'ATT%',
        type: 'attack',
    },
    blockZeroAttack: {
        key: 'zeroAttack',
        name: 'Block Zero Attack',
        label: 'Z',
        type: 'block',
    },
    blockSolo: {
        key: 'blockSolo',
        name: 'Block Solo',
        label: 'BS',
        type: 'block',
    },
    blockAssist: {
        key: 'blockAssist',
        name: 'Block Assist',
        label: 'BA',
        type: 'block',
    },
    blockError: {
        key: 'blockError',
        name: 'Block Error',
        label: 'BE',
        type: 'block',
    },
    blockTotal: {
        key: 'blockTotal',
        name: 'Block Total',
        label: 'Total',
        type: 'block',
    },
    blockPercentage: {
        key: 'blockPercentage',
        name: 'Block %',
        label: 'B%',
        type: 'block',
    },
    settingAssist: {
        key: 'settingAssist',
        name: 'Setting Assist',
        label: 'A',
        type: 'set',
    },
    settingZero: {
        key: 'settingZero',
        name: 'Setting Zero',
        label: 'AZ',
        type: 'set',
    },
    settingError: {
        key: 'settingError',
        name: 'Setting Error',
        label: 'SE',
        type: 'set',
    },
    settingTotal: {
        key: 'settingTotal',
        name: 'Setting Attempts',
        label: 'SA',
        type: 'set',
    },
    settingAssistPercentage: {
        key: 'settingAssistPercentage',
        name: 'Setting Assist %',
        label: 'A%',
        type: 'set',
    },
    settingPercentage: {
        key: 'settingPercentage',
        name: 'Setting %',
        label: 'S%',
        type: 'set',
    },
    dig3: {
        key: 'dig3',
        name: 'Dig 3',
        label: '3',
        type: 'dig',
    },
    dig2: {
        key: 'dig2',
        name: 'Dig 2',
        label: '2',
        type: 'dig',
    },
    dig1: {
        key: 'dig1',
        name: 'Dig 1',
        label: '1',
        type: 'dig',
    },
    dig0: {
        key: 'dig0',
        name: 'Dig 0',
        label: '0',
        type: 'dig',
    },
    digsTotal: {
        key: 'digsTotal',
        name: 'Dig Attempts',
        label: 'DA',
        type: 'dig',
    },
    passingPercentage: {
        key: 'passingPercentage',
        name: 'Passing %',
        label: 'P%',
        type: 'dig',
    },
};
