export const fonts = {
    headerOne: 'text-5xl font-bold tracking-wide sm:text-6xl',
    headerTwo: 'text-4xl lg:text-6xl font-semibold leading-8',
    headerThree: 'text-4xl font-semibold leading-8',
    descriptionTitle: 'text-base leading-7',
    descriptionData: 'text-3xl lg:text-5xl font-semibold tracking-tight',
    historyTitle: 'text-4xl leading-7',
    historyBody: 'text-xl leading-relaxed font-normal',
    navLink: 'text-lg font-semiBold',
    mobileNavText: 'text-lg font-semibold',
    captionXs: 'text-sm font-normal tracking-tight',
    captionSm: 'text-sm font-normal tracking-tight',
    captionMd: 'text-base font-normal tracking-tight',
    mobileHistoryBody: 'text-sm font-normal tracking-normal',
    videoThumbnailTitle: 'text-lg md:text-4xl leading-7',
};
